### ISSUE TITLE
Anchors with accents in Spanish doesn't work

### ISSUE THREAD

**Issue by gboquizosanchez** [RetroAchievements/docs#105]
In Spanish we have accents in our titles, and those titles usually have anchors. If you put an anchor in that link, it doesn't work.

@wescopeland any idea how can we solve this? I'll try to find out something in vitepress documentation.

**Comment by wescopeland** [comment]
Not sure on a good solution, but definitely open to ideas/PRs!

Is it possible to somehow have the anchor link and the title text be two separate things? eg:
```tsx
<div id="foo">Bar</div>
```

**Comment by gboquizosanchez** [comment]
> Not sure on a good solution, but definitely open to ideas/PRs!
> 
> Is it possible to somehow have the anchor link and the title text be two separate things? eg:
> 
> ```tsx
> <div id="foo">Bar</div>
> ```

This is working like a charm. So, I'll put all anchors with accents in this way, thanks @wescopeland Good workaround!
