### ISSUE TITLE
Add pt-BR translation on `/docs/general/about-us.md`

### ISSUE THREAD

**Issue by G3mha** [RetroAchievements/docs#137]
Translates the file `/docs/general/about-us.md` to Portuguese from Brazil.

**Comment by wescopeland** [comment]
Hi! I would be happy to accept a PR on this :) Unfortunately, most of the pt-BR translation for the docs is quite behind. We could probably have dozens of issues open for getting it up to date 😅

If you feel inclined, please feel free to open PRs updating the translation! It does not need to be attached to an issue, I would be happy to accept this contribution. I will close this for now.

Thanks!

**Comment by G3mha** [comment]
@wescopeland I'm a huge fan of the project (as most of you also are), and taking a course on Open Source Development in my college, in which the grades and criteria of approval is contributing to public repositories. RA was one of the first that came to my mind. 

I will be more than happy to contribute to the translation, and having a lot of stuff to work on is even better (more points to me heheh). I hope to be useful to the project!

**Comment by wescopeland** [comment]
That sounds wonderful :)

Any translation task can be pretty overwhelming at first. I've pulled up some analytics for you; these are the pages that users in Brazil specifically are visiting most often:

<img width="552" alt="Screenshot 2024-11-17 at 8 35 46 AM" src="https://github.com/user-attachments/assets/74f13558-1e6c-4465-94f0-5a6af7a3879f">

And these are the most popular pages globally:

<img width="550" alt="Screenshot 2024-11-17 at 8 37 54 AM" src="https://github.com/user-attachments/assets/2bdbd746-7be3-40a6-acb0-7e5ec638b0a2">

These are stats taken from the last 30 days.

**Comment by G3mha** [comment]
@wescopeland Thanks, that helps a lot, I will aim for those first!
