### ISSUE TITLE
create a custom trigger viewer component for the developer docs

### ISSUE THREAD

**Issue by wescopeland** [RetroAchievements/docs#23]
The hits column is still being truncated / requires horizontal scrolling.

Let's have a custom Trigger viewer component for our dev docs. Not sure how feasible this is, but something like this would be great:

```md
::: trigger

| ID  | Flag      | Type  | Size   | Memory | Cmp | Type | Size | Mem/Val | Hits |
| --- | --------- | ----- | ------ | ------ | --- | ---- | ---- | ------- | ---- |
| 1   | SubSource | Delta | 16-bit | 0x1234 |     |      |      |         |      |
| 2   | Remember  | Mem   | 16-bit | 0x1234 |     |      |      |         |      |

:::
```

Then the table would receive special formatting.

**Comment by redwizard42** [comment]
Some of the issue is just that the docs nav on the right and the ... current doc nav on the left just take up enough space that the table content is just a bit too wide for the middle space.
