### ISSUE TITLE
remove or replace the combining flags page

### ISSUE THREAD

**Issue by wescopeland** [RetroAchievements/docs#7]
No longer exists in the nav, only contains two sentences, and only can be directly hyperlinked to.

**Comment by G3mha** [comment]
@wescopeland I wish to tackle this issue! Is the best approach to "track down" all the places where the flags' hyperlinks are, and then replace that hyperlink by the content of the referred file? What do you have in mind?

**Comment by wescopeland** [comment]
Hi @G3mha! Yes, I believe that would be best. Remove the file, and replace any links to the file with the text content itself.
