### ISSUE TITLE
Add a docs page explaining to players what subsets are and how to play them

### ISSUE THREAD

**Issue by wescopeland** [RetroAchievements/docs#94]
"subset" is the top search query on the docs site, but it currently sends people to a developer doc. This is very much less than ideal.

**Comment by SuperGamer18** [comment]
I'm willing to do it. But first, I'm going to ask the following:
Would it be a good idea to copy portions from https://github.com/RetroAchievements/docs/blob/main/docs/guidelines/content/subsets.md this doc? Because it does have a decent amount of information players could understand (obviously I'm not asking to just copy and paste what was done here and only polish it slightly, it's more than just that).

**Comment by wescopeland** [comment]
@SuperGamer18 Hi!

It's probably OK to take inspiration from portions of that document, yes. However, I believe the emphasis should be most tightly focused on:

* Very quickly explaining a subset (3 sentences most for this, maybe link to existing doc if user wants to learn more)
* With both pictures and text, quickly explain how to take an existing ROM and patch it. Search traffic suggests this is what people are looking for and can't find.

Someone should be able to open the page and gather this info in 3 minutes or less.

If successful, we'll link the site directly to the doc.

For content that may be duplicative, it could be best to just link to that existing subsets page. We can then track if people who land on this page navigate there. Based on those behavior patterns we can continue to refine both pages.

**Comment by SuperGamer18** [comment]
Alright, I'll proceed to work on it, thanks for the suggestions, Wes! Also one last question for now, in which directory would you think is the most suitable for putting this in? (This is the first time I make a new file for this repo btw, so I'm not sure where everything should go)

**Comment by wescopeland** [comment]
> Also one last question for now, in which directory would you think is the most suitable for putting this in?

Good question. I think probably in _general/tutorials/how-to-play-subsets.md_.

The sidebar can be updated in _docs/.vitepress/config/en.ts_. I'd put it right underneath the tutorial for PSP DLC:
```ts
{
  text: "Working with DLC for the PlayStation Portable",
  link: "/general/tutorials/working-with-dlc-for-the-psp",
},
{
  text: "How to Play Subsets",
  link: "/general/tutorials/how-to-play-subsets",
},
```

**Comment by SuperGamer18** [comment]
Just made a PR about this, it's #104. As usual, feel free to hit me up with some suggestions (nothing about replacing the screenshots though, sorry).
